In [1]:
import pandas as pd
import numpy as np

### Global

In [2]:
eu_countries = ['Austria','Belgium','Bulgaria','Croatia','Cyprus','Czechia','Denmark','Estonia',\
                'Finland','France','Germany','Greece','Hungary','Ireland','Italy','Latvia','Lithuania',\
                'Luxembourg','Malta','Netherlands','Poland','Portugal','Romania','Slovakia','Slovenia','Spain','Sweden']

eu_code = ['AUT', 'BEL', 'BGR', 'HRV', 'CYP', 'CZE', 'DNK', 'EST', 'FIN',\
                     'FRA', 'DEU', 'GRC', 'HUN', 'IRL', 'ITA', 'LVA', 'LTU', 'LUX',\
                     'MLT', 'NLD', 'POL', 'PRT', 'ROU', 'SVK', 'SVN', 'ESP', 'SWE']

eu_flags = flags_emojis = ['🇦🇹', '🇧🇪', '🇧🇬', '🇭🇷', '🇨🇾', '🇨🇿', '🇩🇰', '🇪🇪', '🇫🇮', '🇫🇷', '🇩🇪', \
                           '🇬🇷', '🇭🇺', '🇮🇪', '🇮🇹', '🇱🇻', '🇱🇹', '🇱🇺', '🇲🇹', '🇳🇱', '🇵🇱', '🇵🇹', \
                           '🇷🇴', '🇸🇰', '🇸🇮', '🇪🇸', '🇸🇪']

# Now, you have a list of flag emojis in the desired order.


final_dataset = pd.DataFrame({'Name': eu_countries, 'Code': eu_code, 'Flag': eu_flags})
final_dataset.head()

Name Code Flag
0   Austria  AUT   🇦🇹
1   Belgium  BEL   🇧🇪
2  Bulgaria  BGR   🇧🇬
3   Croatia  HRV   🇭🇷
4    Cyprus  CYP   🇨🇾

# Aggregation and Cleaning 

### Coruption

In [3]:
df = pd.read_csv('./Corruption/TI-corruption-perception-index.csv')
df.head()

Entity Code  Year  \
0  Afghanistan  AFG  2012   
1  Afghanistan  AFG  2013   
2  Afghanistan  AFG  2014   
3  Afghanistan  AFG  2015   
4  Afghanistan  AFG  2016   

   Corruption Perception Index - Transparency International (2018)  
0                                                  8                
1                                                  8                
2                                                 12                
3                                                 11                
4                                                 15

In [4]:
res = df[(df['Entity'].isin(eu_countries)) & (df['Year'] == 2018) ]

In [5]:
final_dataset = final_dataset.merge(res[['Code', 'Corruption Perception Index - Transparency International (2018)']], on='Code')
final_dataset = final_dataset.rename(columns={'Corruption Perception Index - Transparency International (2018)': 'CorruptionIndex'})
final_dataset.head()

Name Code Flag  CorruptionIndex
0   Austria  AUT   🇦🇹               76
1   Belgium  BEL   🇧🇪               75
2  Bulgaria  BGR   🇧🇬               42
3   Croatia  HRV   🇭🇷               48
4    Cyprus  CYP   🇨🇾               59

### UV Index

In [6]:
df = pd.read_csv('./UVRadiation/data.tsv', sep='\t')
df.head()

Name  Year
0  Afghanistan  4132
1      Albania  2542
2      Algeria  3253
3      Andorra  2469
4       Angola  5287

In [7]:
res = df[(df['Name'].isin(eu_countries))]

In [8]:
final_dataset = final_dataset.merge(res[['Name', 'Year']], on='Name')
final_dataset = final_dataset.rename(columns={'Year': 'UVIndex'})
final_dataset.head()

Name Code Flag  CorruptionIndex  UVIndex
0   Austria  AUT   🇦🇹               76     1888
1   Belgium  BEL   🇧🇪               75     1645
2  Bulgaria  BGR   🇧🇬               42     2331
3   Croatia  HRV   🇭🇷               48     1976
4    Cyprus  CYP   🇨🇾               59     3439

### Obesity

In [9]:
df = pd.read_csv('./Obesity/share-of-adults-defined-as-obese.csv', sep=';')
df.head()

Entity Code  Year  ObesityIndex
0  Afghanistan  AFG  1975           0.4
1  Afghanistan  AFG  1976           0.4
2  Afghanistan  AFG  1977           0.5
3  Afghanistan  AFG  1978           0.5
4  Afghanistan  AFG  1979           0.5

In [10]:
res = df[(df['Entity'].isin(eu_countries)) & (df['Year'] == 2016)]

In [11]:
final_dataset = final_dataset.merge(res[['Code', 'ObesityIndex']], on='Code')
final_dataset.head()

Name Code Flag  CorruptionIndex  UVIndex  ObesityIndex
0   Austria  AUT   🇦🇹               76     1888          21.9
1   Belgium  BEL   🇧🇪               75     1645          24.5
2  Bulgaria  BGR   🇧🇬               42     2331          27.4
3   Croatia  HRV   🇭🇷               48     1976          27.1
4    Cyprus  CYP   🇨🇾               59     3439          22.6

### Hapiness

In [12]:
df = pd.read_csv('./Happiness/Happiness-WVS-vs-Gallup.csv')
df.head()

Entity      Code  Year  Cantril ladder score  \
0     Abkhazia  OWID_ABK  2015                   NaN   
1  Afghanistan       AFG  2022                1.8590   
2  Afghanistan       AFG  2021                2.4038   
3  Afghanistan       AFG  2020                2.5229   
4  Afghanistan       AFG  2019                2.5669   

   Share of people who are happy (World Value Survey 2014)  \
0                                                NaN         
1                                                NaN         
2                                                NaN         
3                                                NaN         
4                                                NaN         

   Population (historical estimates) Continent  
0                                NaN      Asia  
1                                NaN       NaN  
2                         40099460.0       NaN  
3                         38972236.0       NaN  
4                         37769496.0       NaN

In [13]:
res = df[(df['Entity'].isin(eu_countries)) & (df['Year'] == 2018)].loc[:,['Code', 'Cantril ladder score']]

In [14]:
final_dataset = final_dataset.merge(res, on='Code')
final_dataset = final_dataset.rename(columns={'Cantril ladder score': 'HappinessIndex'})
final_dataset.head()

Name Code Flag  CorruptionIndex  UVIndex  ObesityIndex  HappinessIndex
0   Austria  AUT   🇦🇹               76     1888          21.9          7.2460
1   Belgium  BEL   🇧🇪               75     1645          24.5          6.9230
2  Bulgaria  BGR   🇧🇬               42     2331          27.4          5.0110
3   Croatia  HRV   🇭🇷               48     1976          27.1          5.4318
4    Cyprus  CYP   🇨🇾               59     3439          22.6          6.0458

### Drugs death rate

In [15]:
df = pd.read_csv('./Drugs/deaths-illicit-drugs.tsv', sep='\t')
df.head()

Name Code  Year  DrugDeaths
0  Afghanistan  AFG  1990        93.0
1  Afghanistan  AFG  1991       102.0
2  Afghanistan  AFG  1992       118.0
3  Afghanistan  AFG  1993       132.0
4  Afghanistan  AFG  1994       142.0

In [16]:
res = df[(df['Name'].isin(eu_countries)) & (df['Year'] == 2019)]
del res['Year']

In [17]:
final_dataset = final_dataset.merge(res, on='Code')
final_dataset.head()

Name_x Code Flag  CorruptionIndex  UVIndex  ObesityIndex  HappinessIndex  \
0   Austria  AUT   🇦🇹               76     1888          21.9          7.2460   
1   Belgium  BEL   🇧🇪               75     1645          24.5          6.9230   
2  Bulgaria  BGR   🇧🇬               42     2331          27.4          5.0110   
3   Croatia  HRV   🇭🇷               48     1976          27.1          5.4318   
4    Cyprus  CYP   🇨🇾               59     3439          22.6          6.0458   

     Name_y  DrugDeaths  
0   Austria       140.0  
1   Belgium       224.0  
2  Bulgaria        69.0  
3   Croatia        70.0  
4    Cyprus        17.0

### Final

In [18]:
final_dataset = final_dataset.rename(columns={'Name_x': 'Name'})
del final_dataset['Name_y']

In [19]:
final_dataset

Name Code Flag  CorruptionIndex  UVIndex  ObesityIndex  \
0       Austria  AUT   🇦🇹               76     1888          21.9   
1       Belgium  BEL   🇧🇪               75     1645          24.5   
2      Bulgaria  BGR   🇧🇬               42     2331          27.4   
3       Croatia  HRV   🇭🇷               48     1976          27.1   
4        Cyprus  CYP   🇨🇾               59     3439          22.6   
5       Czechia  CZE   🇨🇿               59     1707          28.5   
6       Denmark  DNK   🇩🇰               88     1691          21.3   
7       Estonia  EST   🇪🇪               73     1781          23.8   
8       Finland  FIN   🇫🇮               85     1494          24.9   
9        France  FRA   🇫🇷               72     1907          23.2   
10      Germany  DEU   🇩🇪               80     1812          25.7   
11       Greece  GRC   🇬🇷               45     2753          27.4   
12      Hungary  HUN   🇭🇺               46     1932          28.6   
13      Ireland  IRL   🇮🇪               73     1509          26.9   
14        Italy  ITA   🇮🇹               52     2444          22.9   
15       Latvia  LVA   🇱🇻               58     1671          25.7   
16    Lithuania  LTU   🇱🇹               59     1801          28.4   
17   Luxembourg  LUX   🇱🇺               81     1687          24.2   
18        Malta  MLT   🇲🇹               54     3091          31.0   
19  Netherlands  NLD   🇳🇱               82     1662          23.1   
20       Poland  POL   🇵🇱               60     1749          25.6   
21     Portugal  PRT   🇵🇹               64     2585          23.2   
22      Romania  ROU   🇷🇴               47     2071          24.5   
23     Slovakia  SVK   🇸🇰               50     1795          22.4   
24     Slovenia  SVN   🇸🇮               60     2256          22.5   
25        Spain  ESP   🇪🇸               58     2705          27.1   
26       Sweden  SWE   🇸🇪               85     1587          22.1   

    HappinessIndex  DrugDeaths  
0           7.2460       140.0  
1           6.9230       224.0  
2           5.0110        69.0  
3           5.4318        70.0  
4           6.0458        17.0  
5           6.8521       136.0  
6           7.6001       198.0  
7           5.8935       128.0  
8           7.7689       291.0  
9           6.5921      1839.0  
10          6.9850      1678.0  
11          5.2867       186.0  
12          5.7583        63.0  
13          7.0211       200.0  
14          6.2234       563.0  
15          5.9397        51.0  
16          6.1490       169.0  
17          7.0903        15.0  
18          6.7256         9.0  
19          7.4876       176.0  
20          6.1817       211.0  
21          5.6925        51.0  
22          6.0697       149.0  
23          6.1976        18.0  
24          6.1177        28.0  
25          6.3541       728.0  
26          7.3433       485.0

In [20]:
json_data = final_dataset.to_json(orient='records')

In [21]:
with open('./dataCleaned.json', 'w') as json_file:
    json_file.write(json_data)

# Parsed Data

### Corruption

In [22]:
quartiles = np.percentile(final_dataset['CorruptionIndex'].values, [25, 50, 75])
quartiles

array([53. , 60. , 75.5])

In [23]:
def corruptionClassifier(value, quartiles):
    if value <= quartiles[0]:
        return 'high'
    elif value > quartiles[0] and value <= quartiles[2]:
        return 'neutral'
    else:
        return 'low'

In [24]:
final_dataset['CorruptionIndex_Parsed'] = final_dataset['CorruptionIndex'].apply(corruptionClassifier, args=(quartiles,))

### UV Index

In [25]:
quartiles = np.percentile(final_dataset['UVIndex'].values, [25, 50, 75])
quartiles

array([1689. , 1812. , 2293.5])

In [26]:
def UVClassifier(value, quartiles):
    if value <= quartiles[0]:
        return 'low'
    elif value > quartiles[0] and value <= quartiles[2]:
        return 'neutral'
    else:
        return 'high'

In [27]:
final_dataset['UVIndex_Parsed'] = final_dataset['UVIndex'].apply(UVClassifier, args=(quartiles,))

### Obesity

In [28]:
quartiles = np.percentile(final_dataset['ObesityIndex'].values, [25, 50, 75])
quartiles

array([23. , 24.5, 27.1])

In [29]:
def obesityClassifier(value, quartiles):
    if value <= quartiles[1]:
        return 'low'
    else:
        return 'high'

In [30]:
final_dataset['ObesityIndex_Parsed'] = final_dataset['ObesityIndex'].apply(obesityClassifier, args=(quartiles,))

In [31]:
# final_dataset[final_dataset['ObesityIndex_Parsed'] == 'high']

### Happiness

In [32]:
quartiles = np.percentile(final_dataset['HappinessIndex'].values, [25, 50, 75])
quartiles

array([5.99275, 6.2234 , 7.00305])

In [33]:
def happinessClassifier(value, quartiles):
    if value <= quartiles[0]:
        return 'low'
    elif value > quartiles[0] and value <= quartiles[2]:
        return 'neutral'
    else:
        return 'high'

In [34]:
final_dataset['HappinessIndex_Parsed'] = final_dataset['HappinessIndex'].apply(happinessClassifier, args=(quartiles,))

In [35]:
# final_dataset[final_dataset['HappinessIndex_Parsed'] == 'low']

### Drugs

In [36]:
quartiles = np.percentile(final_dataset['DrugDeaths'].values, [25, 50, 75])
quartiles

array([ 57. , 149. , 217.5])

In [37]:
def drugDeathsClassifier(value, quartiles):
    if value <= quartiles[2]:
        return 'low'
    else:
        return 'high'

In [38]:
final_dataset['DrugDeaths_Parsed'] = final_dataset['DrugDeaths'].apply(drugDeathsClassifier, args=(quartiles,))

### Final

In [39]:
json_data = final_dataset.to_json(orient='records')

In [40]:
# with open('./dataParsed.json', 'w') as json_file:
#     json_file.write(json_data)

In [41]:
final_dataset['ObesityIndex_Parsed'].unique()

array(['low', 'high'], dtype=object)

In [42]:
for column in ['CorruptionIndex_Parsed', 'UVIndex_Parsed', 'ObesityIndex_Parsed', 'HappinessIndex_Parsed', 'DrugDeaths_Parsed']:
    print(column, final_dataset[column].unique())

CorruptionIndex_Parsed ['low' 'neutral' 'high']
UVIndex_Parsed ['neutral' 'low' 'high']
ObesityIndex_Parsed ['low' 'high']
HappinessIndex_Parsed ['high' 'neutral' 'low']
DrugDeaths_Parsed ['low' 'high']
